Getting Started
--------------------------------------------------------------------------------

If you want to learn what the Online Linguistic Database does or how to get and
install it, you should start here.

.. toctree::
   :maxdepth: 2

   about
   installation


Architecture
--------------------------------------------------------------------------------

Look here to find details about the design of the OLD.

.. toctree::
   :maxdepth: 2

   architecture
   interface
   datastructure


Tutorial
--------------------------------------------------------------------------------

This section will contain a whiz-bang! tutorial of the OLD: quick installation,
testing and getting started playing with the system.


API
--------------------------------------------------------------------------------

This section will contain the API documentation automatically extracted from the
docstrings of the source code.


If you can’t find the information you’re looking for, have a look at the index
or try to find it using the search function:


* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`

