Getting Started
--------------------------------------------------------------------------------

If you want to learn what the Online Linguistic Database does or how to get and
install it, you should start here.

.. toctree::
   :maxdepth: 2

   about
   installation


Architecture
--------------------------------------------------------------------------------

Look here to find details about

.. toctree::
   :maxdepth: 2

   architecture
   models
   controllers
   validation
   processing



If you can’t find the information you’re looking for, have a look at the index
or try to find it using the search function:


* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`

